### ISSUE TITLE
Possibility to add an option to download only games and ignore patches?

### ISSUE THREAD

**Issue by Yarg-mirror** [Kalanyr/gogrepoc#104]
Hello,

While reviewing the code/options available I may have answered myself my question. But I was wondering if there was a possibility to skip patches of games and just download the new full release of it where there is an update or during the initial download?

I assume that can be done with simply using `-skipfiles`, and that it is probably the intended way. So sorry if I asked the question for nothing!

Thanks in advance for your time! And for this great project :)

**Comment by Sargon-Aelther** [comment]
Use `-skipfiles patch_*`
