### ISSUE TITLE
Cyberpunk oddities

### ISSUE THREAD

**Issue by Kugelblitz360** [Kalanyr/gogrepoc#105]
Any ideas why Cyberpunk refuses to get to the latest versions, even when you manually force full reload of the manifest of its ID? Is this GOG actively blocking full downloads for every point release? Website has 2.12 for some days now, gogrepoc can only see 2.11.

Cheers, Boris

**Comment by Kalanyr** [comment]
This should be exactly the same as the website ( it uses the same API )
sometimes they don't mark it as updated for a couple of days though, it's
not unusual for the website to be a couple of days behind Galaxy though.

**Comment by Kugelblitz360** [comment]
Yes, they should, and no, they are not.

**Comment by Kalanyr** [comment]
I did just double check though and the links on the website are the
standard ones so even if it's somehow getting an old list the actual files
should be the new ones regardless ( except for any that got added ), unless
this is an issue where the CDN is desynched.

**Comment by Kugelblitz360** [comment]
Current status: The "game items" list stays empty no matter how I refresh. I only can get the Extras. This is only for Cyberpunk and I guess it is blocked out actively by GOG because it is SUCH a massive download. Still annoying.

**Comment by Kalanyr** [comment]
Last time I checked ( at the beginning of the month) it worked normally but
I'll check into this on Friday or Saturday my time.

**Comment by Kugelblitz360** [comment]
STOP PRESS. After totally deleting the manifest file it now works. Sorry for disturbing!
