### ISSUE TITLE
Can't download Atom RPG

### ISSUE THREAD

**Issue by Jaysyn904** [Kalanyr/gogrepoc#109]
Can't download Atom RPG

10:53:51 | ( 24 / 407) fetching game details for atom_rpg_postapocalyptic_indie_game...
10:53:53 | request failed: 404 Client Error: Not Found for url: https://gog-cdn-fastly.gog.com/token=nva=1716389631~dirs=6~token=0774e356615337e130b00/secure/linux_offlines/1673367037/1673367037/57186263152814002/2281/atom_rpg_post_apocalyptic_indie_game_1_190_70193.sh.xml.  will not retry.
10:53:53 | no md5 data found for atom_rpg_post_apocalyptic_indie_game_1_190_70193.sh
10:53:55 | request failed: 404 Client Error: Not Found for url: https://cdn.gog.com/secure/linux_offlines/1673367037/1673367037/57186263152814002/2281/atom_rpg_post_apocalyptic_indie_game_1_190_70193.sh.xml?1223fb43868c5f174d699ac0583ffcf68b0007c0c9dfb2bcf9fd8d557a5d52608f11a35ddeb47e4c3fad684aba38351c88d553151c5f75ad31dc6126ecc536020ad7968c846c29101a52e39e5356fa803b84f2a6ae45bd5b4f21e6d9f447afb3f539d280750ae43edb4d3dfb2af06d2207266cf12654ce7544928042499ff68cb1e868ec48bcec975f377bb7a9686526f8fcbf98c8dba0e9cfe6e1c1479e942f3c359fe976d08c7099a605ab961537cc51b5fb27ec9ea1d32976f675fef004d5c4&fileExtForIe=.exe.  will not retry.
10:53:55 | no md5 data found for atom_rpg_post_apocalyptic_indie_game_1_190_70193.sh
10:53:55 | Successfully fetched file info from https://www.gog.com/downloads/atom_rpg_postapocalyptic_indie_game/en3installer0 but no md5 data was available       
10:53:55 | ( 25 / 407) fetching game details for atomicrops...
10:53:56 | ( 26 / 407) fetching game details for aven_colony...

**Comment by Kalanyr** [comment]
Those aren't fatal errors, they are missing md5s , which just means that if
the corresponding file download gets interrupted it has to start over from
scratch and that the verification is much more heuristic, the downloads
still happen

**Comment by Jaysyn904** [comment]
Yeah, I realized that after I started the actual download process.  My mistake.
