### ISSUE TITLE
Download everything?

### ISSUE THREAD

**Issue by johnstrasser** [Kalanyr/gogrepoc#67]
Dumb question...Don't know if I should ask here or on gog, so doing both...

Is there a simple way to download EVERYTHING. Every language, every installer, every os, everything?

I keep trying different cmd options and all I get is the bonus files. I'm experimenting with the bash script now. But it looks like even that is somewhat limiting.

Any help?

**Comment by Kalanyr** [comment]
You can get all os with windows mac linux
For all languages you'd have to open up the script file and copy out all
the possible languages, there's no built in switch for it.

I'd recommend doing some careful checking before trying this tho, my
collection of English Linux/OS/Mac Games are well over 5 TB just by
themselves.

**Comment by johnstrasser** [comment]
Gotcha. And thanks for the reply. I'll experiment.
