### ISSUE TITLE
Problem logging in 

### ISSUE THREAD

**Issue by hsantos78** [Kalanyr/gogrepoc#70]
I am trying to log in with my user and password. Always fails with **cannot continue, gog is asking for a reCAPTCHA :(  try again in a few minutes.** message. I exported the cookies from firefox with export cookies extension into cookies.txt  into the same folder and got same message. Tried also downloading from chrome with get cookies.txt extension and same  message. What else can I try ?

**Comment by Kalanyr** [comment]
The Recaptcha mark is IP bound so trying to login from a different IP is
probably all you can do.

**Comment by PauloGDPeixoto** [comment]
I'm facing the same issue. Tried changing the IP with a VPN provider, but I always get the same message.

**Comment by pasbec** [comment]
This problem is definitely not solely bound to the IP. I can logout/login from the exact same IP with different browsers and without any captcha.

With this gogrepoc got completey usless for me.

How could this be fixed? Maybe a workaround?

**Comment by Kalanyr** [comment]
This should already be fixed. I switched to token login and changed the
recaptcha detection method, a couple of commits ago. You just need to
download the current version and then login again.

**Comment by pasbec** [comment]
> This should already be fixed. I switched to token login and changed the recaptcha detection method, a couple of commits ago. You just need to download the current version and then login again.

Awesome - thank you very much @Kalanyr! I've probably haven't pulled the latest changes correctly before my first attempt.

**Comment by Wilstorm** [comment]
I was having the exact same issue described in the OP a while back but had to put it aside to work on some other projects. Coming back a few days ago this fixed the issue for me also. Thank you.

**Comment by Kalanyr** [comment]
Woops, forgot to close this.  Feel free to reopen if my guess about how a real Captcha trip would work is wrong.
