### ISSUE TITLE
"no md5 data found for" Error for (nearly) all .sh files

### ISSUE THREAD

**Issue by Sargon-Aelther** [Kalanyr/gogrepoc#99]
I'm not sure if GOG broke something recently or what, but for the past few months I've been getting _"request failed: 404 Client Error: Not Found for url: <...> .sh.xml"_ and _"no md5 data found for"_ errors for pretty much all Linux (.sh) files without exception. Windows and Mac files seem to be fine.

**Comment by Kalanyr** [comment]
I think GOG might be phasing out the website  md5 data for these ( they
have an internal MD5 that can still be used but the loss of chunk data
unfortunately makes resumed downloads have to start from the beginning)

**Comment by Sargon-Aelther** [comment]
I see. Hopefully they'll maintain these for Windows at least.
